crypto_elt_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/crypto.duckdb'
      threads: 4

elementary:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/crypto.duckdb'
      schema: elementary
      threads: 1
